### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by xuyuan** [BerlinUnited/humanoid_walk_tutorials#1]
Hi @mellmann just followed your new project, and remember that I have participated the nao race in 2015, and tried out my old code, wow it still works exactly the same, and 1st in benchmark now :D

I havent work on this topic for some time, hope you will get and share better solution. Have fun!

**Comment by efcy** [comment]
Hi @xuyuan do you have your old code somewhere or is it still secret?

**Comment by xuyuan** [comment]
Hi @BenjiSchlotter there is no secret, it is same approach as we participated in RoboCup simulation league in 2010: genetic algorithm was used to optimize parameters of robocup motion (c++ code, python binding, LIP based walking algorithm) in webots, and then recorded the joint angles of each frame and replay the frames in online benchmark (webots is so deterministic).

However the code is not open sourced, the optimization and race with webots is easy to release (only some python files), but the robocup motion code is much more complicated as part of the whole dainamite code base. We wanted to open source, but were too lazy :/ and there is no motivation to do it now.
